// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"hightouch/internal/sdk"
	"hightouch/internal/sdk/pkg/models/shared"

	"github.com/hashicorp/terraform-plugin-framework-validators/mapvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"hightouch/internal/sdk/pkg/models/operations"
	"hightouch/internal/validators"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &SyncResource{}
var _ resource.ResourceWithImportState = &SyncResource{}

func NewSyncResource() resource.Resource {
	return &SyncResource{}
}

// SyncResource defines the resource implementation.
type SyncResource struct {
	client *sdk.Hightouch
}

// SyncResourceModel describes the resource data model.
type SyncResourceModel struct {
	Configuration     map[string]types.String `tfsdk:"configuration"`
	CreatedAt         types.String            `tfsdk:"created_at"`
	DestinationID     types.String            `tfsdk:"destination_id"`
	Details           map[string]types.String `tfsdk:"details"`
	Disabled          types.Bool              `tfsdk:"disabled"`
	ID                types.String            `tfsdk:"id"`
	LastRunAt         types.String            `tfsdk:"last_run_at"`
	Message           types.String            `tfsdk:"message"`
	ModelID           types.String            `tfsdk:"model_id"`
	PrimaryKey        types.String            `tfsdk:"primary_key"`
	ReferencedColumns []types.String          `tfsdk:"referenced_columns"`
	Schedule          SyncCreateSchedule      `tfsdk:"schedule"`
	Slug              types.String            `tfsdk:"slug"`
	Status            types.String            `tfsdk:"status"`
	Type              types.String            `tfsdk:"type"`
	UpdatedAt         types.String            `tfsdk:"updated_at"`
	WorkspaceID       types.String            `tfsdk:"workspace_id"`
}

func (r *SyncResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_sync"
}

func (r *SyncResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Sync Resource",

		Attributes: map[string]schema.Attribute{
			"configuration": schema.MapAttribute{
				Required:    true,
				ElementType: types.StringType,
				Validators: []validator.Map{
					mapvalidator.ValueStringsAre(validators.IsValidJSON()),
				},
				MarkdownDescription: `The sync's configuration. This specifies how data is mapped, among other` + "\n" +
					`configuration.` + "\n" +
					`` + "\n" +
					`The schema depends on the destination type.` + "\n" +
					`` + "\n" +
					`Consumers should NOT make assumptions on the contents of the` + "\n" +
					`configuration. It may change as Hightouch updates its internal code.`,
			},
			"created_at": schema.StringAttribute{
				Computed: true,
				Validators: []validator.String{
					validators.IsRFC3339(),
				},
				Description: `The timestamp when the sync was created`,
			},
			"destination_id": schema.StringAttribute{
				Required:    true,
				Description: `The id of the Destination that sync is connected to`,
			},
			"details": schema.MapAttribute{
				Computed:    true,
				ElementType: types.StringType,
				Validators: []validator.Map{
					mapvalidator.ValueStringsAre(validators.IsValidJSON()),
				},
			},
			"disabled": schema.BoolAttribute{
				Required:    true,
				Description: `Whether the sync has been disabled by the user.`,
			},
			"id": schema.StringAttribute{
				Computed:    true,
				Description: `The sync's id`,
			},
			"last_run_at": schema.StringAttribute{
				Computed: true,
				Validators: []validator.String{
					validators.IsRFC3339(),
				},
				Description: `The timestamp of the last sync run`,
			},
			"message": schema.StringAttribute{
				Computed: true,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"Validation failed",
					),
				},
				Description: `must be one of [Validation failed]`,
			},
			"model_id": schema.StringAttribute{
				Required:    true,
				Description: `The id of the Model that sync is connected to`,
			},
			"primary_key": schema.StringAttribute{
				Computed:    true,
				Description: `The primary key that sync uses to identify data from source`,
			},
			"referenced_columns": schema.ListAttribute{
				Computed:    true,
				ElementType: types.StringType,
				Description: `The reference column that sync depends on to sync data from source`,
			},
			"schedule": schema.SingleNestedAttribute{
				Required: true,
				Attributes: map[string]schema.Attribute{
					"schedule": schema.SingleNestedAttribute{
						Computed: true,
						Attributes: map[string]schema.Attribute{
							"interval_schedule": schema.SingleNestedAttribute{
								Computed: true,
								Attributes: map[string]schema.Attribute{
									"interval": schema.SingleNestedAttribute{
										Computed: true,
										Attributes: map[string]schema.Attribute{
											"quantity": schema.NumberAttribute{
												Computed: true,
											},
											"unit": schema.StringAttribute{
												Computed: true,
												Validators: []validator.String{
													stringvalidator.OneOf(
														"minute",
														"hour",
														"day",
														"week",
													),
												},
												Description: `must be one of [minute, hour, day, week]`,
											},
										},
									},
								},
							},
							"cron_schedule": schema.SingleNestedAttribute{
								Computed: true,
								Attributes: map[string]schema.Attribute{
									"expression": schema.StringAttribute{
										Computed: true,
									},
								},
							},
							"visual_cron_schedule": schema.SingleNestedAttribute{
								Computed: true,
								Attributes: map[string]schema.Attribute{
									"expressions": schema.ListNestedAttribute{
										Computed: true,
										NestedObject: schema.NestedAttributeObject{
											Attributes: map[string]schema.Attribute{
												"days": schema.SingleNestedAttribute{
													Computed: true,
													Attributes: map[string]schema.Attribute{
														"friday": schema.BoolAttribute{
															Computed: true,
														},
														"monday": schema.BoolAttribute{
															Computed: true,
														},
														"saturday": schema.BoolAttribute{
															Computed: true,
														},
														"sunday": schema.BoolAttribute{
															Computed: true,
														},
														"thursday": schema.BoolAttribute{
															Computed: true,
														},
														"tuesday": schema.BoolAttribute{
															Computed: true,
														},
														"wednesday": schema.BoolAttribute{
															Computed: true,
														},
													},
													Description: `Construct a type with a set of properties K of type T`,
												},
												"time": schema.StringAttribute{
													Computed: true,
												},
											},
										},
									},
								},
							},
							"dbt_schedule": schema.SingleNestedAttribute{
								Computed: true,
								Attributes: map[string]schema.Attribute{
									"account": schema.SingleNestedAttribute{
										Computed: true,
										Attributes: map[string]schema.Attribute{
											"id": schema.StringAttribute{
												Computed: true,
											},
										},
									},
									"dbt_credential_id": schema.StringAttribute{
										Computed: true,
									},
									"job": schema.SingleNestedAttribute{
										Computed: true,
										Attributes: map[string]schema.Attribute{
											"id": schema.StringAttribute{
												Computed: true,
											},
										},
									},
								},
							},
						},
						Validators: []validator.Object{
							validators.ExactlyOneChild(),
						},
					},
					"type": schema.StringAttribute{
						Computed: true,
					},
				},
				MarkdownDescription: `The scheduling configuration. It can be triggerd based on several ways:` + "\n" +
					`` + "\n" +
					`Interval: the sync will be trigged based on certain interval(minutes/hours/days/weeks)` + "\n" +
					`` + "\n" +
					`Cron: the sync will be trigged based on cron expression https://en.wikipedia.org/wiki/Cron.` + "\n" +
					`` + "\n" +
					`Visual: the sync will be trigged based a visual cron configuration on UI` + "\n" +
					`` + "\n" +
					`DBT-cloud: the sync will be trigged based on a dbt cloud job`,
			},
			"slug": schema.StringAttribute{
				Required:    true,
				Description: `The sync's slug`,
			},
			"status": schema.StringAttribute{
				Computed: true,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"disabled",
						"pending",
						"cancelled",
						"failed",
						"queued",
						"success",
						"warning",
						"querying",
						"processing",
						"reporting",
						"interrupted",
					),
				},
				MarkdownDescription: `must be one of [disabled, pending, cancelled, failed, queued, success, warning, querying, processing, reporting, interrupted]` + "\n" +
					`SyncStatus`,
			},
			"type": schema.StringAttribute{
				Required: true,
			},
			"updated_at": schema.StringAttribute{
				Computed: true,
				Validators: []validator.String{
					validators.IsRFC3339(),
				},
				Description: `The timestamp when the sync was last updated`,
			},
			"workspace_id": schema.StringAttribute{
				Computed:    true,
				Description: `The id of the workspace that the sync belongs to`,
			},
		},
	}
}

func (r *SyncResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.Hightouch)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *sdk.Hightouch, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *SyncResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data *SyncResourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Plan.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	configuration := make(map[string]interface{})
	// Warning. This is a map, but the source tf var is not a map. This might indicate a bug.
	destinationID := data.DestinationID.ValueString()
	disabled := data.Disabled.ValueBool()
	modelID := data.ModelID.ValueString()
	var schedule1 shared.SyncCreateScheduleSchedule
	var intervalSchedule *shared.IntervalSchedule
	if data.Schedule != nil {
		quantity, _ := data.Schedule.Quantity.ValueBigFloat().Float64()
		unit := shared.IntervalUnit(data.Schedule.Unit.ValueString())
		interval := shared.Interval{
			Quantity: quantity,
			Unit:     unit,
		}
		intervalSchedule = &shared.IntervalSchedule{
			Interval: interval,
		}
	}
	if intervalSchedule != nil {
		schedule1 = shared.SyncCreateScheduleSchedule{
			IntervalSchedule: intervalSchedule,
		}
	}
	var cronSchedule *shared.CronSchedule
	if data.Schedule != nil {
		expression := data.Schedule.Expression.ValueString()
		cronSchedule = &shared.CronSchedule{
			Expression: expression,
		}
	}
	if cronSchedule != nil {
		schedule1 = shared.SyncCreateScheduleSchedule{
			CronSchedule: cronSchedule,
		}
	}
	var visualCronSchedule *shared.VisualCronSchedule
	if data.Schedule != nil {
		var expressions []shared.VisualCronScheduleExpressions = nil
		for _, expressionsItem := range data.Schedule.Expressions {
			friday := new(bool)
			if !expressionsItem.Friday.IsUnknown() && !expressionsItem.Friday.IsNull() {
				*friday = expressionsItem.Friday.ValueBool()
			} else {
				friday = nil
			}
			monday := new(bool)
			if !expressionsItem.Monday.IsUnknown() && !expressionsItem.Monday.IsNull() {
				*monday = expressionsItem.Monday.ValueBool()
			} else {
				monday = nil
			}
			saturday := new(bool)
			if !expressionsItem.Saturday.IsUnknown() && !expressionsItem.Saturday.IsNull() {
				*saturday = expressionsItem.Saturday.ValueBool()
			} else {
				saturday = nil
			}
			sunday := new(bool)
			if !expressionsItem.Sunday.IsUnknown() && !expressionsItem.Sunday.IsNull() {
				*sunday = expressionsItem.Sunday.ValueBool()
			} else {
				sunday = nil
			}
			thursday := new(bool)
			if !expressionsItem.Thursday.IsUnknown() && !expressionsItem.Thursday.IsNull() {
				*thursday = expressionsItem.Thursday.ValueBool()
			} else {
				thursday = nil
			}
			tuesday := new(bool)
			if !expressionsItem.Tuesday.IsUnknown() && !expressionsItem.Tuesday.IsNull() {
				*tuesday = expressionsItem.Tuesday.ValueBool()
			} else {
				tuesday = nil
			}
			wednesday := new(bool)
			if !expressionsItem.Wednesday.IsUnknown() && !expressionsItem.Wednesday.IsNull() {
				*wednesday = expressionsItem.Wednesday.ValueBool()
			} else {
				wednesday = nil
			}
			days := shared.RecordDayBooleanOrUndefined{
				Friday:    friday,
				Monday:    monday,
				Saturday:  saturday,
				Sunday:    sunday,
				Thursday:  thursday,
				Tuesday:   tuesday,
				Wednesday: wednesday,
			}
			time := expressionsItem.Time.ValueString()
			expressions = append(expressions, shared.VisualCronScheduleExpressions{
				Days: days,
				Time: time,
			})
		}
		visualCronSchedule = &shared.VisualCronSchedule{
			Expressions: expressions,
		}
	}
	if visualCronSchedule != nil {
		schedule1 = shared.SyncCreateScheduleSchedule{
			VisualCronSchedule: visualCronSchedule,
		}
	}
	var dbtSchedule *shared.DBTSchedule
	if data.Schedule != nil {
		id := data.Schedule.ID.ValueString()
		account := shared.DBTScheduleAccount{
			ID: id,
		}
		dbtCredentialID := data.Schedule.DbtCredentialID.ValueString()
		id1 := data.Schedule.ID.ValueString()
		job := shared.DBTScheduleJob{
			ID: id1,
		}
		dbtSchedule = &shared.DBTSchedule{
			Account:         account,
			DbtCredentialID: dbtCredentialID,
			Job:             job,
		}
	}
	if dbtSchedule != nil {
		schedule1 = shared.SyncCreateScheduleSchedule{
			DBTSchedule: dbtSchedule,
		}
	}
	type1 := data.Type.ValueString()
	schedule := shared.SyncCreateSchedule{
		Schedule: schedule1,
		Type:     type1,
	}
	slug := data.Slug.ValueString()
	request := shared.SyncCreate{
		Configuration: configuration,
		DestinationID: destinationID,
		Disabled:      disabled,
		ModelID:       modelID,
		Schedule:      schedule,
		Slug:          slug,
	}
	res, err := r.client.CreateSync(ctx, request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if res.ValidateErrorJSON == nil {
		resp.Diagnostics.AddError("unexpected response from API. No response body", debugResponse(res.RawResponse))
		return
	}
	data.RefreshFromCreateResponse(res.ValidateErrorJSON)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *SyncResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data *SyncResourceModel
	var item types.Object

	resp.Diagnostics.Append(req.State.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	id := data.ID.ValueString()
	request := operations.GetSyncRequest{
		ID: id,
	}
	res, err := r.client.GetSync(ctx, request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if res.Sync == nil {
		resp.Diagnostics.AddError("unexpected response from API. No response body", debugResponse(res.RawResponse))
		return
	}
	data.RefreshFromGetResponse(res.Sync)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *SyncResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data *SyncResourceModel
	merge(ctx, req, resp, &data)
	if resp.Diagnostics.HasError() {
		return
	}

	configuration := make(map[string]interface{})
	// Warning. This is a map, but the source tf var is not a map. This might indicate a bug.
	disabled := new(bool)
	if !data.Disabled.IsUnknown() && !data.Disabled.IsNull() {
		*disabled = data.Disabled.ValueBool()
	} else {
		disabled = nil
	}
	var schedule *shared.SyncUpdateSchedule
	var schedule1 shared.SyncUpdateScheduleSchedule
	var intervalSchedule *shared.IntervalSchedule
	if data.Schedule != nil {
		quantity, _ := data.Schedule.Quantity.ValueBigFloat().Float64()
		unit := shared.IntervalUnit(data.Schedule.Unit.ValueString())
		interval := shared.Interval{
			Quantity: quantity,
			Unit:     unit,
		}
		intervalSchedule = &shared.IntervalSchedule{
			Interval: interval,
		}
	}
	if intervalSchedule != nil {
		schedule1 = shared.SyncUpdateScheduleSchedule{
			IntervalSchedule: intervalSchedule,
		}
	}
	var cronSchedule *shared.CronSchedule
	if data.Schedule != nil {
		expression := data.Schedule.Expression.ValueString()
		cronSchedule = &shared.CronSchedule{
			Expression: expression,
		}
	}
	if cronSchedule != nil {
		schedule1 = shared.SyncUpdateScheduleSchedule{
			CronSchedule: cronSchedule,
		}
	}
	var visualCronSchedule *shared.VisualCronSchedule
	if data.Schedule != nil {
		var expressions []shared.VisualCronScheduleExpressions = nil
		for _, expressionsItem := range data.Schedule.Expressions {
			friday := new(bool)
			if !expressionsItem.Friday.IsUnknown() && !expressionsItem.Friday.IsNull() {
				*friday = expressionsItem.Friday.ValueBool()
			} else {
				friday = nil
			}
			monday := new(bool)
			if !expressionsItem.Monday.IsUnknown() && !expressionsItem.Monday.IsNull() {
				*monday = expressionsItem.Monday.ValueBool()
			} else {
				monday = nil
			}
			saturday := new(bool)
			if !expressionsItem.Saturday.IsUnknown() && !expressionsItem.Saturday.IsNull() {
				*saturday = expressionsItem.Saturday.ValueBool()
			} else {
				saturday = nil
			}
			sunday := new(bool)
			if !expressionsItem.Sunday.IsUnknown() && !expressionsItem.Sunday.IsNull() {
				*sunday = expressionsItem.Sunday.ValueBool()
			} else {
				sunday = nil
			}
			thursday := new(bool)
			if !expressionsItem.Thursday.IsUnknown() && !expressionsItem.Thursday.IsNull() {
				*thursday = expressionsItem.Thursday.ValueBool()
			} else {
				thursday = nil
			}
			tuesday := new(bool)
			if !expressionsItem.Tuesday.IsUnknown() && !expressionsItem.Tuesday.IsNull() {
				*tuesday = expressionsItem.Tuesday.ValueBool()
			} else {
				tuesday = nil
			}
			wednesday := new(bool)
			if !expressionsItem.Wednesday.IsUnknown() && !expressionsItem.Wednesday.IsNull() {
				*wednesday = expressionsItem.Wednesday.ValueBool()
			} else {
				wednesday = nil
			}
			days := shared.RecordDayBooleanOrUndefined{
				Friday:    friday,
				Monday:    monday,
				Saturday:  saturday,
				Sunday:    sunday,
				Thursday:  thursday,
				Tuesday:   tuesday,
				Wednesday: wednesday,
			}
			time := expressionsItem.Time.ValueString()
			expressions = append(expressions, shared.VisualCronScheduleExpressions{
				Days: days,
				Time: time,
			})
		}
		visualCronSchedule = &shared.VisualCronSchedule{
			Expressions: expressions,
		}
	}
	if visualCronSchedule != nil {
		schedule1 = shared.SyncUpdateScheduleSchedule{
			VisualCronSchedule: visualCronSchedule,
		}
	}
	var dbtSchedule *shared.DBTSchedule
	if data.Schedule != nil {
		id := data.Schedule.ID.ValueString()
		account := shared.DBTScheduleAccount{
			ID: id,
		}
		dbtCredentialID := data.Schedule.DbtCredentialID.ValueString()
		id1 := data.Schedule.ID.ValueString()
		job := shared.DBTScheduleJob{
			ID: id1,
		}
		dbtSchedule = &shared.DBTSchedule{
			Account:         account,
			DbtCredentialID: dbtCredentialID,
			Job:             job,
		}
	}
	if dbtSchedule != nil {
		schedule1 = shared.SyncUpdateScheduleSchedule{
			DBTSchedule: dbtSchedule,
		}
	}
	type1 := data.Type.ValueString()
	schedule = &shared.SyncUpdateSchedule{
		Schedule: schedule1,
		Type:     type1,
	}
	syncUpdate := shared.SyncUpdate{
		Configuration: configuration,
		Disabled:      disabled,
		Schedule:      schedule,
	}
	id2 := data.ID.ValueString()
	request := operations.UpdateSyncRequest{
		SyncUpdate: syncUpdate,
		ID:         id2,
	}
	res, err := r.client.UpdateSync(ctx, request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if res.ValidateErrorJSON == nil {
		resp.Diagnostics.AddError("unexpected response from API. No response body", debugResponse(res.RawResponse))
		return
	}
	data.RefreshFromUpdateResponse(res.ValidateErrorJSON)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *SyncResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data *SyncResourceModel
	var item types.Object

	resp.Diagnostics.Append(req.State.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Not Implemented; entity does not have a configured DELETE operation
}

func (r *SyncResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
