// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"hightouch/internal/sdk"
	"hightouch/internal/sdk/pkg/models/operations"

	"github.com/hashicorp/terraform-plugin-framework-validators/mapvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"hightouch/internal/validators"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &SyncDataSource{}
var _ datasource.DataSourceWithConfigure = &SyncDataSource{}

func NewSyncDataSource() datasource.DataSource {
	return &SyncDataSource{}
}

// SyncDataSource is the data source implementation.
type SyncDataSource struct {
	client *sdk.Hightouch
}

// SyncDataSourceModel describes the data model.
type SyncDataSourceModel struct {
	Configuration     map[string]types.String `tfsdk:"configuration"`
	CreatedAt         types.String            `tfsdk:"created_at"`
	DestinationID     types.String            `tfsdk:"destination_id"`
	Disabled          types.Bool              `tfsdk:"disabled"`
	ID                types.String            `tfsdk:"id"`
	LastRunAt         types.String            `tfsdk:"last_run_at"`
	ModelID           types.String            `tfsdk:"model_id"`
	PrimaryKey        types.String            `tfsdk:"primary_key"`
	ReferencedColumns []types.String          `tfsdk:"referenced_columns"`
	Schedule          SyncCreateSchedule      `tfsdk:"schedule"`
	Slug              types.String            `tfsdk:"slug"`
	Status            types.String            `tfsdk:"status"`
	UpdatedAt         types.String            `tfsdk:"updated_at"`
	WorkspaceID       types.String            `tfsdk:"workspace_id"`
}

// Metadata returns the data source type name.
func (r *SyncDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_sync"
}

// Schema defines the schema for the data source.
func (r *SyncDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Sync DataSource",

		Attributes: map[string]schema.Attribute{
			"configuration": schema.MapAttribute{
				Computed:    true,
				ElementType: types.StringType,
				Validators: []validator.Map{
					mapvalidator.ValueStringsAre(validators.IsValidJSON()),
				},
				MarkdownDescription: `The sync's configuration. This specifies how data is mapped, among other` + "\n" +
					`configuration.` + "\n" +
					`` + "\n" +
					`The schema depends on the destination type.` + "\n" +
					`` + "\n" +
					`Consumers should NOT make assumptions on the contents of the` + "\n" +
					`configuration. It may change as Hightouch updates its internal code.`,
			},
			"created_at": schema.StringAttribute{
				Computed: true,
				Validators: []validator.String{
					validators.IsRFC3339(),
				},
				Description: `The timestamp when the sync was created`,
			},
			"destination_id": schema.StringAttribute{
				Computed:    true,
				Description: `The id of the Destination that sync is connected to`,
			},
			"disabled": schema.BoolAttribute{
				Computed:    true,
				Description: `Whether the sync has been disabled by the user.`,
			},
			"id": schema.StringAttribute{
				Required:    true,
				Description: `The id of the sync`,
			},
			"last_run_at": schema.StringAttribute{
				Computed: true,
				Validators: []validator.String{
					validators.IsRFC3339(),
				},
				Description: `The timestamp of the last sync run`,
			},
			"model_id": schema.StringAttribute{
				Computed:    true,
				Description: `The id of the Model that sync is connected to`,
			},
			"primary_key": schema.StringAttribute{
				Computed:    true,
				Description: `The primary key that sync uses to identify data from source`,
			},
			"referenced_columns": schema.ListAttribute{
				Computed:    true,
				ElementType: types.StringType,
				Description: `The reference column that sync depends on to sync data from source`,
			},
			"schedule": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"schedule": schema.SingleNestedAttribute{
						Computed: true,
						Attributes: map[string]schema.Attribute{
							"interval_schedule": schema.SingleNestedAttribute{
								Computed: true,
								Attributes: map[string]schema.Attribute{
									"interval": schema.SingleNestedAttribute{
										Computed: true,
										Attributes: map[string]schema.Attribute{
											"quantity": schema.NumberAttribute{
												Computed: true,
											},
											"unit": schema.StringAttribute{
												Computed: true,
												Validators: []validator.String{
													stringvalidator.OneOf(
														"minute",
														"hour",
														"day",
														"week",
													),
												},
												Description: `must be one of [minute, hour, day, week]`,
											},
										},
									},
								},
							},
							"cron_schedule": schema.SingleNestedAttribute{
								Computed: true,
								Attributes: map[string]schema.Attribute{
									"expression": schema.StringAttribute{
										Computed: true,
									},
								},
							},
							"visual_cron_schedule": schema.SingleNestedAttribute{
								Computed: true,
								Attributes: map[string]schema.Attribute{
									"expressions": schema.ListNestedAttribute{
										Computed: true,
										NestedObject: schema.NestedAttributeObject{
											Attributes: map[string]schema.Attribute{
												"days": schema.SingleNestedAttribute{
													Computed: true,
													Attributes: map[string]schema.Attribute{
														"friday": schema.BoolAttribute{
															Computed: true,
														},
														"monday": schema.BoolAttribute{
															Computed: true,
														},
														"saturday": schema.BoolAttribute{
															Computed: true,
														},
														"sunday": schema.BoolAttribute{
															Computed: true,
														},
														"thursday": schema.BoolAttribute{
															Computed: true,
														},
														"tuesday": schema.BoolAttribute{
															Computed: true,
														},
														"wednesday": schema.BoolAttribute{
															Computed: true,
														},
													},
													Description: `Construct a type with a set of properties K of type T`,
												},
												"time": schema.StringAttribute{
													Computed: true,
												},
											},
										},
									},
								},
							},
							"dbt_schedule": schema.SingleNestedAttribute{
								Computed: true,
								Attributes: map[string]schema.Attribute{
									"account": schema.SingleNestedAttribute{
										Computed: true,
										Attributes: map[string]schema.Attribute{
											"id": schema.StringAttribute{
												Computed: true,
											},
										},
									},
									"dbt_credential_id": schema.StringAttribute{
										Computed: true,
									},
									"job": schema.SingleNestedAttribute{
										Computed: true,
										Attributes: map[string]schema.Attribute{
											"id": schema.StringAttribute{
												Computed: true,
											},
										},
									},
								},
							},
						},
						Validators: []validator.Object{
							validators.ExactlyOneChild(),
						},
					},
					"type": schema.StringAttribute{
						Computed: true,
					},
				},
				MarkdownDescription: `The scheduling configuration. It can be triggerd based on several ways:` + "\n" +
					`` + "\n" +
					`Interval: the sync will be trigged based on certain interval(minutes/hours/days/weeks)` + "\n" +
					`` + "\n" +
					`Cron: the sync will be trigged based on cron expression https://en.wikipedia.org/wiki/Cron.` + "\n" +
					`` + "\n" +
					`Visual: the sync will be trigged based a visual cron configuration on UI` + "\n" +
					`` + "\n" +
					`DBT-cloud: the sync will be trigged based on a dbt cloud job`,
			},
			"slug": schema.StringAttribute{
				Computed:    true,
				Description: `The sync's slug`,
			},
			"status": schema.StringAttribute{
				Computed: true,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"disabled",
						"pending",
						"cancelled",
						"failed",
						"queued",
						"success",
						"warning",
						"querying",
						"processing",
						"reporting",
						"interrupted",
					),
				},
				MarkdownDescription: `must be one of [disabled, pending, cancelled, failed, queued, success, warning, querying, processing, reporting, interrupted]` + "\n" +
					`SyncStatus`,
			},
			"updated_at": schema.StringAttribute{
				Computed: true,
				Validators: []validator.String{
					validators.IsRFC3339(),
				},
				Description: `The timestamp when the sync was last updated`,
			},
			"workspace_id": schema.StringAttribute{
				Computed:    true,
				Description: `The id of the workspace that the sync belongs to`,
			},
		},
	}
}

func (r *SyncDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.Hightouch)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *sdk.Hightouch, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *SyncDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *SyncDataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	id := data.ID.ValueString()
	request := operations.GetSyncRequest{
		ID: id,
	}
	res, err := r.client.GetSync(ctx, request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if res.Sync == nil {
		resp.Diagnostics.AddError("unexpected response from API. No response body", debugResponse(res.RawResponse))
		return
	}
	data.RefreshFromGetResponse(res.Sync)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
