// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type ModelCreateDbt struct {
	CompiledSQL types.String `tfsdk:"compiled_sql"`
	Database    types.String `tfsdk:"database"`
	DbtUniqueID types.String `tfsdk:"dbt_unique_id"`
	ModelID     types.String `tfsdk:"model_id"`
	Name        types.String `tfsdk:"name"`
	RawSQL      types.String `tfsdk:"raw_sql"`
	Schema      types.String `tfsdk:"schema"`
}
