// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

type SyncCreateScheduleSchedule struct {
	CronSchedule       *CronSchedule       `tfsdk:"cron_schedule"`
	DBTSchedule        *DBTSchedule        `tfsdk:"dbt_schedule"`
	IntervalSchedule   *IntervalSchedule   `tfsdk:"interval_schedule"`
	VisualCronSchedule *VisualCronSchedule `tfsdk:"visual_cron_schedule"`
}
