// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type ModelCreateVisual struct {
	Filter         types.String `tfsdk:"filter"`
	ParentID       types.String `tfsdk:"parent_id"`
	PrimaryLabel   types.String `tfsdk:"primary_label"`
	SecondaryLabel types.String `tfsdk:"secondary_label"`
}
