// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type VisualCronScheduleExpressions struct {
	Days RecordDayBooleanOrUndefined `tfsdk:"days"`
	Time types.String                `tfsdk:"time"`
}
