// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type Interval struct {
	Quantity types.Number `tfsdk:"quantity"`
	Unit     types.String `tfsdk:"unit"`
}
