// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type CronSchedule struct {
	Expression types.String `tfsdk:"expression"`
}
