// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"hightouch/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetDestinationRequest struct {
	// The destination's ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type GetDestinationResponse struct {
	ContentType string
	// Ok
	Destination *shared.Destination
	StatusCode  int
	RawResponse *http.Response
}
