// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"hightouch/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetSourceRequest struct {
	// The id of the source
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type GetSourceResponse struct {
	ContentType string
	// Ok
	Source      *shared.Source
	StatusCode  int
	RawResponse *http.Response
	// Validation Failed
	ValidateErrorJSON *shared.ValidateErrorJSON
}
